### ISSUE TITLE
java.lang.AssertionError: No such value argument slot in IrConstructorCallImpl: 2 (total=2) when upgrading from 2.4.0 to 2.5.0

### ISSUE THREAD

**Issue by 0xnm** [lupuuss/Mokkery#106]
Hello,

There is a regression when upgrading from version `2.4.0` to `2.5.0` of Mokkery, test sources compilation fails with the following error:

```
e: Compilation failed: No such value argument slot in IrConstructorCallImpl: 2 (total=2).
Symbol: dev.mokkery.context/CallArgument.<init>|<init>(kotlin.Any?;dev.mokkery.context.Function.Parameter){}[0]
Expression: CONSTRUCTOR_CALL 'internal constructor <init> (value: kotlin.Any?, parameter: dev.mokkery.context.Function.Parameter) [primary] declared in dev.mokkery.context.CallArgument' type=dev.mokkery.context.CallArgument origin=null
 * Source files: FailingTest.kt
 * Compiler version: 2.0.21
 * Output kind: LIBRARY
e: java.lang.AssertionError: No such value argument slot in IrConstructorCallImpl: 2 (total=2).
Symbol: dev.mokkery.context/CallArgument.<init>|<init>(kotlin.Any?;dev.mokkery.context.Function.Parameter){}[0]
Expression: CONSTRUCTOR_CALL 'internal constructor <init> (value: kotlin.Any?, parameter: dev.mokkery.context.Function.Parameter) [primary] declared in dev.mokkery.context.CallArgument' type=dev.mokkery.context.CallArgument origin=null
	at org.jetbrains.kotlin.ir.expressions.IrExpressionsKt.checkArgumentSlotAccess(IrExpressions.kt:75)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.putValueArgument(IrMemberAccessExpression.kt:50)
	at dev.mokkery.plugin.transformers.IrInterceptCallKt.irCallArgsList(IrInterceptCall.kt:96)
	at dev.mokkery.plugin.transformers.IrInterceptCallKt.irInterceptCall(IrInterceptCall.kt:81)
	at dev.mokkery.plugin.transformers.IrInterceptCallKt.irInterceptMethod(IrInterceptCall.kt:50)
	at dev.mokkery.plugin.transformers.BuildMockClassKt.mockBody(BuildMockClass.kt:186)
	at dev.mokkery.plugin.transformers.BuildMockClassKt.buildMockClass$lambda$2(BuildMockClass.kt:113)
	at dev.mokkery.plugin.ir.IrClassKt.addOverridingMethod(IrClass.kt:75)
	at dev.mokkery.plugin.ir.IrClassKt.addOverridingMethod(IrClass.kt:50)
	at dev.mokkery.plugin.ir.IrClassKt.overrideAllOverridableFunctions(IrClass.kt:87)
	at dev.mokkery.plugin.transformers.BuildMockClassKt.buildMockClass(BuildMockClass.kt:112)
	at dev.mokkery.plugin.transformers.MokkeryTransformer.replaceWithMock$lambda$1(MokkeryTransformer.kt:95)
	at dev.mokkery.plugin.core.HashMapCache.getOrPut(Cache.kt:22)
	at dev.mokkery.plugin.transformers.MokkeryTransformer.replaceWithMock(MokkeryTransformer.kt:95)
	at dev.mokkery.plugin.transformers.MokkeryTransformer.visitCall(MokkeryTransformer.kt:67)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:299)
        ...
```

The same issue happens at least in the 2.8.0 as well, just the wording is different since compiler API changed.

It is quite easy to reproduce it:

**commonMain**
```
interface FakeType {
    fun doSomething(arg: String)
}
```

**iosTest**
```
class FailingTest {

    @Test
    fun test() {
        val mock = mock<FakeType>()

        mock.doSomething("something")
    }
}
```

The issue goes away if signature of `doSomething(arg: String)` is changed to `doSomething()`, so by removing the argument.

**Comment by 0xnm** [comment]
I'm sorry, my bad, it was a typo: it should be from 2.4.0 to 2.5.0, I updated the issue.

**Comment by lupuuss** [comment]
Thanks for confirming! Are you unable to update your Kotlin version? I just want to understand the need for the backport, since I haven’t been able to reproduce the issue and can’t tell how many users are affected.

If you are affected, I can release a backported fix with 2.7.3, as the 2.7.2 version supports a wider range of Kotlin versions than 2.8.0.

**Comment by lupuuss** [comment]
Ok, sure. I will notify you when the backport fix is released.

**Comment by lupuuss** [comment]
I've published `2.7.3-SNAPSHOT`. @0xnm could you please verify that it works? I will release it fully once it's confirmed.

Here is snapshots repository:
```kotlin
maven { url = uri("https://central.sonatype.com/repository/maven-snapshots/") }
```

**Comment by 0xnm** [comment]
Hello @lupuuss!

I can confirm that `2.7.3-SNAPSHOT` solves the issue. Thanks for your support.

**Comment by lupuuss** [comment]
@0xnm version `2.7.3` is out!
